
server:
  port: 8080
  
eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
       
spring:
 application:
  name: apigateway
 cloud:
   gateway:
     routes:
     - id: gobierno-chihuahua
       uri: lb://gobierno-chihuahua
       predicates:
       - Path=/controlador/**