eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
spring:
  application:
    name: gobierno-chihuahua
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    password: passw0rd
    url: jdbc:db2://10.27.22.208:50000/od_bcpl
    username: db2inst1
  jackson:
    locale: es_MX
    time-zone: America/Mexico_City
    #habilitar documentacion swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html  
    #  packagesToScan: com.bancoppel.billing.entities, com.bancoppel.billing.controller
    #  pathsToMatch: /v1, /billing/**  